// Mocks generated by Mockito 5.0.16 from annotations
// in weather_app/test/data/repositories/weather_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;
import 'package:weather_app/data/datasources/remote/weather_service.dart'
    as _i3;
import 'package:weather_app/data/model/get_regions_response.dart' as _i5;
import 'package:weather_app/data/model/get_weather_details_response.dart'
    as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeHttpResponse_0<T> extends _i1.Fake implements _i2.HttpResponse<T> {}

/// A class which mocks [WeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherService extends _i1.Mock implements _i3.WeatherService {
  MockWeatherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<List<_i5.RegionItem>>> getRegions(
          String? lattlong) =>
      (super.noSuchMethod(Invocation.method(#getRegions, [lattlong]),
              returnValue: Future<_i2.HttpResponse<List<_i5.RegionItem>>>.value(
                  _FakeHttpResponse_0<List<_i5.RegionItem>>()))
          as _i4.Future<_i2.HttpResponse<List<_i5.RegionItem>>>);
  @override
  _i4.Future<_i2.HttpResponse<_i6.GetWeatherDetailsResponse>> getWeatherData(
          int? woeid) =>
      (super.noSuchMethod(Invocation.method(#getWeatherData, [woeid]),
              returnValue:
                  Future<_i2.HttpResponse<_i6.GetWeatherDetailsResponse>>.value(
                      _FakeHttpResponse_0<_i6.GetWeatherDetailsResponse>()))
          as _i4.Future<_i2.HttpResponse<_i6.GetWeatherDetailsResponse>>);
  @override
  String toString() => super.toString();
}
