// Mocks generated by Mockito 5.0.16 from annotations
// in weather_app/test/domain/usecases/region/get_user_region_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/core/resource/resource.dart' as _i3;
import 'package:weather_app/data/datasources/remote/weather_service.dart'
    as _i2;
import 'package:weather_app/data/repositories/weather.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeWeatherService_0 extends _i1.Fake implements _i2.WeatherService {}

class _FakeResource_1<T> extends _i1.Fake implements _i3.Resource<T> {}

/// A class which mocks [WeatherRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepositoryImpl extends _i1.Mock
    implements _i4.WeatherRepositoryImpl {
  MockWeatherRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WeatherService get service =>
      (super.noSuchMethod(Invocation.getter(#service),
          returnValue: _FakeWeatherService_0()) as _i2.WeatherService);
  @override
  set service(_i2.WeatherService? _service) =>
      super.noSuchMethod(Invocation.setter(#service, _service),
          returnValueForMissingStub: null);
  @override
  _i5.Future<_i3.Resource<dynamic>> getRegions(double? late, double? long) =>
      (super.noSuchMethod(Invocation.method(#getRegions, [late, long]),
              returnValue: Future<_i3.Resource<dynamic>>.value(
                  _FakeResource_1<dynamic>()))
          as _i5.Future<_i3.Resource<dynamic>>);
  @override
  _i5.Future<_i3.Resource<dynamic>> getWeatherData(int? woeid) =>
      (super.noSuchMethod(Invocation.method(#getWeatherData, [woeid]),
              returnValue: Future<_i3.Resource<dynamic>>.value(
                  _FakeResource_1<dynamic>()))
          as _i5.Future<_i3.Resource<dynamic>>);
  @override
  String toString() => super.toString();
}
